### ISSUE TITLE
other players who arent host cant see items colours

### ISSUE THREAD

**Issue by Jenssons** [EvanTich/ror2-modding#1]
so like what title says, only i can see what items are what colours when they change. but everyone else still see them as their normal colours

**Comment by EvanTich** [comment]
Can you give any more information about what you experienced? Which mod? None of mine change item colors or UI.

**Comment by Jenssons** [comment]
MoreArtifacts woops i went to the wrong Artifact mod i am very sorry

**Comment by EvanTich** [comment]
This **is** the repo for MoreArtifacts. I assume you meant another mod is causing the issue. Closing.
