### ISSUE TITLE
One of the Artifacts hard crashes the game in Void Fields

### ISSUE THREAD

**Issue by cheeeeeeeeeen** [EvanTich/ror2-modding#3]
One of the artifacts in Void Fields crashes the game. There's no errors found from Unity or the console. Disabling the mod resolves the issue.

**Comment by EvanTich** [comment]
Which one of the artifacts were you using or were you using both of them? What was happening at the time? Give a little more information.

**Comment by cheeeeeeeeeen** [comment]
It was the Artifact that merges monsters into a bigger one. In my experience, at least, that happened. It also happens for other people as reported in the Discord Server. It only happens in Void Fields.

**Comment by EvanTich** [comment]
Alright, I'm fairly certain I fixed it. I did a few runs through the Void Fields to make sure it works. I changed a single line to fix this.
