### ISSUE TITLE
Has this stopped working with the anniversary update?

### ISSUE THREAD

**Issue by redcatelf** [EvanTich/ror2-modding#4]
I'm just trying this for the first time, and I'm not seeing any new artifacts. Could it be that this mod stopped working with the RoR2 anniversary update?

**Comment by EvanTich** [comment]
It turns out it doesn't work... I was under the assumption that somebody would come to me sooner if my mod wasn't working. Thanks for bringing this to my attention. I'll fix it ASAP.

**Comment by EvanTich** [comment]
Latest version of the mod addresses this issue. Enjoy!
