### ISSUE TITLE
Float parse error

### ISSUE THREAD

**Issue by KingEnderBrine** [EvanTich/ror2-modding#5]
https://github.com/EvanTich/ror2-modding/blob/ab0a32749783c5d7545eaf999ec1703951e986c5/MoreArtifacts/MoreArtifactsConfig.cs#L55
float.Parse(numberString) may not always parse numbers as you would expect. For example, in a system with the Russian language, it would use a format with a comma for decimal sign instead of dot, e.g `1,1` which would result in a parsing error for `1.1`.
If you want it to always use dot as a decimal point you should use
```cs
float.Parse(g[1].Trim(), System.Globalization.NumberFormatInfo.InvariantInfo);
```

**Comment by EvanTich** [comment]
Are all the other floating point numbers formatted in the correct way (`1,1` instead of `1.1`)? If so, it would be better to change the config entry so it saves to the config in the correct way instead?

**Comment by KingEnderBrine** [comment]
BepInEx also uses `InvariantInfo` when it parses numbers:
https://github.com/BepInEx/BepInEx/blob/048943c322f7c907ec065c2a56f5be61052b57ef/BepInEx.Core/Configuration/TomlTypeConverter.cs#L85-L89
I would say `1.1` is better than `1,1` since it's a standard way in programming. And you anyway use `1.1` format in config description.
https://github.com/EvanTich/ror2-modding/blob/ab0a32749783c5d7545eaf999ec1703951e986c5/MoreArtifacts/MoreArtifactsConfig.cs#L126-L130

**Comment by EvanTich** [comment]
Fixed with latest Thunderstore release and commit 4e4caa7b06c760be7536afd94e3483c51337734e.
